In [188]:
# Postulante: Georgina Viviana Quiroz Mendoza
# Docente: Marcelo Palma
# Modulo: BUSINESS INTELLIGENT Y MINERIA DE DATOS

# 1. Carga y exploración inicial (15 min)
# Importación de librerías necesarias
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Cargar los datos (puedes cambiar la ruta por el nombre de tu archivo si lo estás usando desde CSV)
data = pd.read_csv("E:/MAESTRIA/MOD4/PRACTICAS/PRACTICA2/transacciones.csv", sep=",")

In [189]:
# Visualizar las primeras filas
print("Primeras filas del dataset:")
display(data.head())

Primeras filas del dataset:

,Unnamed: 0,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,...,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,PreviousTransactionDate,DaysSinceLastTransaction,TransactionHour,IsWeekendTransaction,IsFraud
0,0,TX000001,AC00128,14.09,2023-04-11 16:29:14,Debit,San Diego,D000380,162.198.218.92,M015,...,70,Doctor,81,1,5112.21,2024-11-04 08:08:08,-573,16,0,0
1,1,TX000002,AC00455,376.24,2023-06-27 16:44:19,Debit,Houston,D000051,13.149.61.4,M052,...,68,Doctor,141,1,13758.91,2024-11-04 08:09:35,-496,16,0,0
2,2,TX000003,AC00019,126.29,2023-07-10 18:16:08,Debit,Mesa,D000235,215.97.143.157,M009,...,19,Student,56,1,1122.35,2024-11-04 08:07:04,-483,18,0,0
3,3,TX000004,AC00070,184.50,2023-05-05 16:32:11,Debit,Raleigh,D000187,200.13.225.150,M002,...,26,Student,25,1,8569.06,2024-11-04 08:09:06,-549,16,0,0
4,4,TX000005,AC00411,13.45,2023-10-16 17:51:24,Credit,Atlanta,D000308,65.164.3.100,M091,...,26,Student,198,1,7429.40,2024-11-04 08:06:39,-385,17,0,0

In [206]:
# 2. Explorar y limpiar los datos
# Ver información general del dataset
print(data.info())

# Verificar valores nulos por columna
print("\nValores nulos por columna:")
print(data.isnull().sum())

# Verificar duplicados
print("\nNúmero de filas duplicadas:")
print(data.duplicated().sum())

# Eliminar duplicados si los hay
data = data.drop_duplicates()
print(data.dtypes)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2512 entries, 0 to 2511
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                2512 non-null   int64
 1   TransactionID             2512 non-null   category
 2   AccountID                 2512 non-null   category
 3   TransactionAmount         2512 non-null   float64
 4   TransactionDate           2512 non-null   datetime64[ns]
 5   TransactionType           2512 non-null   category
 6   Location                  2512 non-null   category
 7   DeviceID                  2512 non-null   category
 8   IP Address                2512 non-null   category
 9   MerchantID                2512 non-null   category
 10  Channel                   2512 non-null   category
 11  CustomerAge               2512 non-null   int64
 12  CustomerOccupation        2512 non-null   category
 13  TransactionDuration       2512 non-null   int64
 14  LoginAttempts             2512 non-null   int64
 15  AccountBalance            2512 non-null   float64
 16  PreviousTransactionDate   2512 non-null   datetime64[ns]
 17  DaysSinceLastTransaction  2512 non-null   int64
 18  TransactionHour           2512 non-null   int64
 19  IsWeekendTransaction      2512 non-null   int64
 20  IsFraud                   2512 non-null   int64
dtypes: category(9), datetime64[ns](2), float64(2), int64(8)
memory usage: 420.7 KB
None

Valores nulos por columna:
Unnamed: 0                  0
TransactionID               0
AccountID                   0
TransactionAmount           0
TransactionDate             0
TransactionType             0
Location                    0
DeviceID                    0
IP Address                  0
MerchantID                  0
Channel                     0
CustomerAge                 0
CustomerOccupation          0
TransactionDuration         0
LoginAttempts               0
AccountBalance              0
PreviousTransactionDate     0
DaysSinceLastTransaction    0
TransactionHour             0
IsWeekendTransaction        0
IsFraud                     0
dtype: int64

Número de filas duplicadas:
0
Unnamed: 0                           int64
TransactionID                     category
AccountID                         category
TransactionAmount                  float64
TransactionDate             datetime64[ns]
TransactionType                   category
Location                          category
DeviceID                          category
IP Address                        category
MerchantID                        category
Channel                           category
CustomerAge                          int64
CustomerOccupation                category
TransactionDuration                  int64
LoginAttempts                        int64
AccountBalance                     float64
PreviousTransactionDate     datetime64[ns]
DaysSinceLastTransaction             int64
TransactionHour                      int64
IsWeekendTransaction                 int64
IsFraud                              int64
dtype: object

In [191]:
data['TransactionID'] = data['TransactionID'].astype('category')
data['AccountID'] = data['AccountID'].astype('category')
data['TransactionDate'] = pd.to_datetime(data['TransactionDate'])
data['TransactionType'] = data['TransactionType'].astype('category')
data['Location'] = data['Location'].astype('category')
data['DeviceID'] = data['DeviceID'].astype('category')
data['IP Address'] = data['IP Address'].astype('category')
data['MerchantID'] = data['MerchantID'].astype('category')
data['Channel'] = data['Channel'].astype('category')
data['CustomerOccupation'] = data['CustomerOccupation'].astype('category')
data['PreviousTransactionDate'] = pd.to_datetime(data['PreviousTransactionDate'])
print(data.dtypes)

Unnamed: 0                           int64
TransactionID                     category
AccountID                         category
TransactionAmount                  float64
TransactionDate             datetime64[ns]
TransactionType                   category
Location                          category
DeviceID                          category
IP Address                        category
MerchantID                        category
Channel                           category
CustomerAge                          int64
CustomerOccupation                category
TransactionDuration                  int64
LoginAttempts                        int64
AccountBalance                     float64
PreviousTransactionDate     datetime64[ns]
DaysSinceLastTransaction             int64
TransactionHour                      int64
IsWeekendTransaction                 int64
IsFraud                              int64
dtype: object

In [207]:
# Resumen completo del DataFrame 'data'
resumen = pd.DataFrame({
    'Columna': data.columns,
    'Tipo de Dato': data.dtypes.values,
    'Valores Únicos': data.nunique().values,
    'Nulos': data.isnull().sum().values,
    'Ejemplo de Valor': [data[col].dropna().iloc[0] if data[col].notna().any() else None for col in data.columns],
    'Es Categórico': [str(data[col].dtype) == 'category' for col in data.columns],
    'Media (si aplica)': [data[col].mean() if pd.api.types.is_numeric_dtype(data[col]) else None for col in data.columns]
})

# Mostrar el resumen
print(resumen)

                     Columna    Tipo de Dato  Valores Únicos  Nulos  \
0                 Unnamed: 0           int64            2512      0
1              TransactionID        category            2512      0
2                  AccountID        category             495      0
3          TransactionAmount         float64            2455      0
4            TransactionDate  datetime64[ns]            2512      0
5            TransactionType        category               2      0
6                   Location        category              43      0
7                   DeviceID        category             681      0
8                 IP Address        category             592      0
9                 MerchantID        category             100      0
10                   Channel        category               3      0
11               CustomerAge           int64              63      0
12        CustomerOccupation        category               4      0
13       TransactionDuration           int64             288      0
14             LoginAttempts           int64               5      0
15            AccountBalance         float64            2510      0
16   PreviousTransactionDate  datetime64[ns]             360      0
17  DaysSinceLastTransaction           int64             261      0
18           TransactionHour           int64               3      0
19      IsWeekendTransaction           int64               1      0
20                   IsFraud           int64               2      0

       Ejemplo de Valor  Es Categórico  Media (si aplica)
0                     0          False        1255.500000
1              TX000001           True                NaN
2               AC00128           True                NaN
3                 14.09          False         297.593778
4   2023-04-11 16:29:14          False                NaN
5                 Debit           True                NaN
6             San Diego           True                NaN
7               D000380           True                NaN
8        162.198.218.92           True                NaN
9                  M015           True                NaN
10                  ATM           True                NaN
11                   70          False          44.673965
12               Doctor           True                NaN
13                   81          False         119.643312
14                    1          False           1.124602
15              5112.21          False        5114.302966
16  2024-11-04 08:08:08          False                NaN
17                 -573          False        -487.857882
18                   16          False          16.626194
19                    0          False           0.000000
20                    0          False           0.006369

In [208]:
# Ver estadísticas descriptivas (incluyendo datos categóricos)
print(data.describe(include='all'))

         Unnamed: 0 TransactionID AccountID  TransactionAmount  \
count   2512.000000          2512      2512        2512.000000
unique          NaN          2512       495                NaN
top             NaN      TX000001   AC00202                NaN
freq            NaN             1        12                NaN
mean    1255.500000           NaN       NaN         297.593778
min        0.000000           NaN       NaN           0.260000
25%      627.750000           NaN       NaN          81.885000
50%     1255.500000           NaN       NaN         211.140000
75%     1883.250000           NaN       NaN         414.527500
max     2511.000000           NaN       NaN        1919.110000
std      725.296261           NaN       NaN         291.946243

                      TransactionDate TransactionType    Location DeviceID  \
count                            2512            2512        2512     2512
unique                            NaN               2          43      681
top                               NaN           Debit  Fort Worth  D000203
freq                              NaN            1944          70        9
mean    2023-07-05 20:32:10.826433024             NaN         NaN      NaN
min               2023-01-02 16:00:06             NaN         NaN      NaN
25%     2023-04-03 16:22:05.750000128             NaN         NaN      NaN
50%        2023-07-07 17:49:43.500000             NaN         NaN      NaN
75%        2023-10-06 18:40:53.500000             NaN         NaN      NaN
max               2024-01-01 18:21:50             NaN         NaN      NaN
std                               NaN             NaN         NaN      NaN

            IP Address MerchantID  ...  CustomerAge  CustomerOccupation  \
count             2512       2512  ...  2512.000000                2512
unique             592        100  ...          NaN                   4
top     200.136.146.93       M026  ...          NaN             Student
freq                13         45  ...          NaN                 657
mean               NaN        NaN  ...    44.673965                 NaN
min                NaN        NaN  ...    18.000000                 NaN
25%                NaN        NaN  ...    27.000000                 NaN
50%                NaN        NaN  ...    45.000000                 NaN
75%                NaN        NaN  ...    59.000000                 NaN
max                NaN        NaN  ...    80.000000                 NaN
std                NaN        NaN  ...    17.792198                 NaN

       TransactionDuration  LoginAttempts  AccountBalance  \
count          2512.000000    2512.000000     2512.000000
unique                 NaN            NaN             NaN
top                    NaN            NaN             NaN
freq                   NaN            NaN             NaN
mean            119.643312       1.124602     5114.302966
min              10.000000       1.000000      101.250000
25%              63.000000       1.000000     1504.370000
50%             112.500000       1.000000     4735.510000
75%             161.000000       1.000000     7678.820000
max             300.000000       5.000000    14977.990000
std              69.963757       0.602662     3900.942499

              PreviousTransactionDate DaysSinceLastTransaction  \
count                            2512              2512.000000
unique                            NaN                      NaN
top                               NaN                      NaN
freq                              NaN                      NaN
mean    2024-11-04 08:09:22.219745024              -487.857882
min               2024-11-04 08:06:23              -672.000000
25%               2024-11-04 08:07:53              -581.000000
50%               2024-11-04 08:09:22              -486.000000
75%     2024-11-04 08:10:53.249999872              -395.000000
max               2024-11-04 08:12:23              -308.000000
std                               NaN               106.378910

        TransactionHour  IsWeekendTransaction      IsFraud
count       2512.000000                2512.0  2512.000000
unique              NaN                   NaN          NaN
top                 NaN                   NaN          NaN
freq                NaN                   NaN          NaN
mean          16.626194                   0.0     0.006369
min           16.000000                   0.0     0.000000
25%           16.000000                   0.0     0.000000
50%           16.000000                   0.0     0.000000
75%           17.000000                   0.0     0.000000
max           18.000000                   0.0     1.000000
std            0.731059                   0.0     0.079570

[11 rows x 21 columns]

In [194]:
print(data.columns.tolist())

['Unnamed: 0', 'TransactionID', 'AccountID', 'TransactionAmount', 'TransactionDate', 'TransactionType', 'Location', 'DeviceID', 'IP Address', 'MerchantID', 'Channel', 'CustomerAge', 'CustomerOccupation', 'TransactionDuration', 'LoginAttempts', 'AccountBalance', 'PreviousTransactionDate', 'DaysSinceLastTransaction', 'TransactionHour', 'IsWeekendTransaction', 'IsFraud']

In [209]:
# 4: Aplicación de Algoritmos de Clasificación se compara dos algoritmos: Árbol de Decisión y Random Forest para predecir la variable objetivo IsFraud.
# 4.1 Dividir en variables predictoras y objetivo
from sklearn.model_selection import train_test_split

# Definir X (predictoras) e y (objetivo)
X = data.drop('IsFraud', axis=1)
y = data['IsFraud']

# División de los datos en conjunto de entrenamiento y prueba (80%/20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [152]:
print(X_train.shape)
print(y_train.shape)

(2009, 20)
(2009,)

In [210]:
#Verificar valores nulos en X_train y y_train

# Verificar valores nulos en X_train
print("Valores nulos en X_train:\n", X_train.isnull().sum())

# Verificar valores nulos en y_train
print("Valores nulos en y_train:\n", y_train.isnull().sum())

# Si hay valores nulos,  optar por eliminar o rellenarlos
X_train = X_train.dropna()  # Eliminar filas con valores nulos en X_train
y_train = y_train[X_train.index]  # Asegurarte de que y_train mantenga el mismo tamaño

# O puedes rellenar valores nulos con un valor específico, por ejemplo 0:
# X_train = X_train.fillna(0)  # Rellenar valores nulos con 0

Valores nulos en X_train:
 Unnamed: 0                  0
TransactionID               0
AccountID                   0
TransactionAmount           0
TransactionDate             0
TransactionType             0
Location                    0
DeviceID                    0
IP Address                  0
MerchantID                  0
Channel                     0
CustomerAge                 0
CustomerOccupation          0
TransactionDuration         0
LoginAttempts               0
AccountBalance              0
PreviousTransactionDate     0
DaysSinceLastTransaction    0
TransactionHour             0
IsWeekendTransaction        0
dtype: int64
Valores nulos en y_train:
 0

In [211]:
# Asegurémonos de que 'TransactionDay' esté presente en el conjunto de datos
if 'TransactionDay' not in X_train.columns:
    # Si no está presente, crearla a partir de la columna 'TransactionDate'
    X_train['TransactionDay'] = X_train['TransactionDate'].dt.day_name()

# Verificar las primeras filas de X_train para asegurar que 'TransactionDay' existe
print(X_train.head())

# Ahora realizamos el One-Hot Encoding
categorical_columns = ['TransactionType', 'Location', 'DeviceID', 'MerchantID', 'Channel', 'CustomerOccupation', 'TransactionDay']
X_train = pd.get_dummies(X_train, columns=categorical_columns, drop_first=True)

# Verificar si ahora todas las columnas son numéricas
print("Tipos de datos en X_train después de la limpieza:\n", X_train.dtypes)

      Unnamed: 0 TransactionID AccountID  TransactionAmount  \
2445        2445      TX002446   AC00439             403.01
2005        2005      TX002006   AC00066             347.25
2472        2472      TX002473   AC00275             113.03
235          235      TX000236   AC00175              54.03
1804        1804      TX001805   AC00274              17.42

         TransactionDate TransactionType      Location DeviceID  \
2445 2023-09-04 17:32:35           Debit    Washington  D000677
2005 2023-01-30 18:49:52           Debit  Indianapolis  D000646
2472 2023-03-15 17:53:09          Credit        Tucson  D000521
235  2023-09-19 17:16:46          Credit     Milwaukee  D000519
1804 2023-11-08 17:24:54           Debit        Dallas  D000516

           IP Address MerchantID  ... CustomerAge  CustomerOccupation  \
2445    223.32.70.156       M029  ...          63              Doctor
2005     33.28.138.82       M062  ...          69              Doctor
2472      11.3.59.231       M001  ...          36              Doctor
235      161.25.82.11       M087  ...          56             Retired
1804  218.238.171.184       M006  ...          74             Retired

     TransactionDuration  LoginAttempts  AccountBalance  \
2445                 286              3        10513.52
2005                 250              1         7273.55
2472                  12              1         6756.13
235                  161              1         6736.30
1804                 150              1         6851.31

      PreviousTransactionDate DaysSinceLastTransaction  TransactionHour  \
2445      2024-11-04 08:09:32                     -427               17
2005      2024-11-04 08:08:01                     -644               18
2472      2024-11-04 08:08:48                     -600               17
235       2024-11-04 08:07:36                     -412               17
1804      2024-11-04 08:12:14                     -362               17

      IsWeekendTransaction  TransactionDay
2445                     0          Monday
2005                     0          Monday
2472                     0       Wednesday
235                      0         Tuesday
1804                     0       Wednesday

[5 rows x 21 columns]
Tipos de datos en X_train después de la limpieza:
 Unnamed: 0                             int64
TransactionID                       category
AccountID                           category
TransactionAmount                    float64
TransactionDate               datetime64[ns]
                                   ...
CustomerOccupation_Student              bool
TransactionDay_Monday                   bool
TransactionDay_Thursday                 bool
TransactionDay_Tuesday                  bool
TransactionDay_Wednesday                bool
Length: 845, dtype: object

In [214]:
#4.2 Entrenar Árbol de Decisión
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, classification_report
import pandas as pd

# Paso previo: Verificar qué columnas categóricas están realmente en X_train
categorical_columns_all = ['TransactionType', 'Location', 'DeviceID', 'MerchantID', 'Channel', 'CustomerOccupation']
available_categorical = [col for col in categorical_columns_all if col in X_train.columns]

print("Columnas categóricas disponibles para codificar:", available_categorical)

# Aplicar get_dummies solo a las columnas disponibles
X_train = pd.get_dummies(X_train, columns=available_categorical, drop_first=True)
X_test = pd.get_dummies(X_test, columns=available_categorical, drop_first=True)

# Alinear columnas entre train y test
X_test = X_test.reindex(columns=X_train.columns, fill_value=0)

# Eliminar columnas datetime si hay
datetime_cols_train = X_train.select_dtypes(include='datetime64').columns
datetime_cols_test = X_test.select_dtypes(include='datetime64').columns
X_train = X_train.drop(columns=datetime_cols_train, errors='ignore')
X_test = X_test.drop(columns=datetime_cols_test, errors='ignore')

# Convertir las columnas que no son numéricas a tipo numérico
# Esto incluye convertir las columnas que contienen texto a valores numéricos
X_train = X_train.apply(pd.to_numeric, errors='coerce')
X_test = X_test.apply(pd.to_numeric, errors='coerce')

# Entrenar el modelo
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)

# Predicción
y_pred_dt = dt_model.predict(X_test)

# Resultados
print(confusion_matrix(y_test, y_pred_dt))
print(classification_report(y_test, y_pred_dt))

Columnas categóricas disponibles para codificar: []
[[499   1]
 [  3   0]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       500
           1       0.00      0.00      0.00         3

    accuracy                           0.99       503
   macro avg       0.50      0.50      0.50       503
weighted avg       0.99      0.99      0.99       503

In [218]:
# Verificar las columnas disponibles en X_train
print(X_train.columns)

Index(['Unnamed: 0', 'TransactionID', 'AccountID', 'TransactionAmount',
       'IP Address', 'CustomerAge', 'TransactionDuration', 'LoginAttempts',
       'AccountBalance', 'DaysSinceLastTransaction',
       ...
       'MerchantID_M100', 'Channel_Branch', 'Channel_Online',
       'CustomerOccupation_Engineer', 'CustomerOccupation_Retired',
       'CustomerOccupation_Student', 'TransactionDay_Monday',
       'TransactionDay_Thursday', 'TransactionDay_Tuesday',
       'TransactionDay_Wednesday'],
      dtype='object', length=843)

In [219]:
#4.3 Entrenar Random Forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report

# Entrenar el modelo directamente (sin pipeline, porque ya está codificado)
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Hacer predicciones
y_pred_rf = rf_model.predict(X_test)

# Evaluación
print("=== Random Forest ===")
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

=== Random Forest ===
[[500   0]
 [  3   0]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       500
           1       0.00      0.00      0.00         3

    accuracy                           0.99       503
   macro avg       0.50      0.50      0.50       503
weighted avg       0.99      0.99      0.99       503

c:\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [220]:
#Evaluación del Árbol de Decisión

from sklearn.metrics import classification_report, confusion_matrix

# Matriz de confusión
print("Matriz de Confusión:")
print(confusion_matrix(y_test, y_pred_dt))

# Reporte de métricas
print("\nReporte de Clasificación:")
print(classification_report(y_test, y_pred_dt))

Matriz de Confusión:
[[499   1]
 [  3   0]]

Reporte de Clasificación:
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       500
           1       0.00      0.00      0.00         3

    accuracy                           0.99       503
   macro avg       0.50      0.50      0.50       503
weighted avg       0.99      0.99      0.99       503

In [247]:
# 5.1 Validación Cruzada con cross_val_score

from sklearn.model_selection import cross_val_score

# Validación cruzada con 5 particiones
cv_scores_dt = cross_val_score(dt_model, X, y, cv=5, scoring='f1')
cv_scores_rf = cross_val_score(rf_model, X, y, cv=5, scoring='f1')

print("F1-score promedio - Árbol de Decisión:", cv_scores_dt.mean())
print("F1-score promedio - Random Forest:", cv_scores_rf.mean())

F1-score promedio - Árbol de Decisión: 0.9333333333333332
F1-score promedio - Random Forest: 0.16

In [237]:
# Eliminar columnas no relevantes
data_clean = data.drop(columns=['TransactionID', 'Location', 'DeviceID', 'IP Address', 'MerchantID'])

In [238]:
# Convertir variables categóricas a variables dummy (One-Hot Encoding)
data_clean = pd.get_dummies(data_clean, columns=['TransactionType', 'Channel', 'CustomerOccupation'], drop_first=True)

In [241]:
# Asegurarnos de que los valores sean numéricos
data_clean = data_clean.apply(pd.to_numeric, errors='coerce')  # Convierte los valores a numéricos, los no numéricos se convierten a NaN
# Manejar los valores NaN
# Imputar valores NaN con la media de la columna
data_clean = data_clean.fillna(data_clean.mean())

In [248]:
# Separar características y variable objetivo
X = data_clean.drop(columns=['IsFraud'])
y = data_clean['IsFraud']

In [249]:
#Realizar validación cruzada
#Finalmente, realizamos la validación cruzada con los modelos de clasificación (por ejemplo, Árboles de Decisión y Random Forest) para evaluar su rendimiento.


from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Modelos
dt_model = DecisionTreeClassifier(random_state=42)
rf_model = RandomForestClassifier(random_state=42)

# Validación cruzada con 5 particiones (F1-score)
cv_scores_dt = cross_val_score(dt_model, X, y, cv=5, scoring='f1')
cv_scores_rf = cross_val_score(rf_model, X, y, cv=5, scoring='f1')

# Promedio de F1-score
print("F1-score promedio - Árbol de Decisión:", cv_scores_dt.mean())
print("F1-score promedio - Random Forest:", cv_scores_rf.mean())

F1-score promedio - Árbol de Decisión: 0.9333333333333332
F1-score promedio - Random Forest: 0.16